server {
    listen 80;
    server_name _;
    root /opt/aq-crm/frontend;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:8097/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin {
        try_files /admin.html =404;
    }

    location /static/ {
        alias /opt/aq-crm/frontend/static/;
    }

    location / {
        try_files $uri /index.html;
    }
}
